sudo: false

dist: "xenial"

addons:
  apt:
    sources:
      - "llvm-toolchain-xenial-8"
    packages:
      - "libllvm8"
      - "llvm-8"
      - "llvm-8-dev"

language: "rust"

rust:
  - "1.41.1"

cache:
  bundler: true
  cargo: true

before_install:
  # Keep this Bundler version in sync with `Gemfile.lock`.
  - "gem install bundler -v '2.0.2'"
  - "bundle install --jobs=3 --retry=3"
  - "export LLVM_SYS_80_PREFIX=$(llvm-config-8 --prefix)"

before_script:
  - "cargo build --verbose"

script:
  - "cargo test --verbose"
  # "bundle exec rspec"
