sudo: false

language: rust

rust:
  - "1.37.0"

before_install:
  # Keep this Bundler version in sync with `Gemfile.lock`.
  - "gem install bundler -v '2.0.2'"
  - "bundle install --jobs=3 --retry=3"

before_script:
  - "cargo build --verbose"

script:
  - "cargo test --verbose"
  - "bundle exec rspec"
