[package]
name = "hummingbird"
version = "0.1.0"
authors = ["Dirk Gadsden <dirk@esherido.com>"]
edition = "2018"

[dependencies]
codespan = "0.4.1"
codespan-reporting = "0.4.1"
lazy_static = "1.3.0"
termcolor = "1.0.5"
